ALTER TABLE `upload_assets`
  ADD COLUMN `scanStatus` VARCHAR(191) NOT NULL DEFAULT 'NOT_REQUIRED',
  ADD COLUMN `scanResult` TEXT NULL,
  ADD COLUMN `uploadedAt` DATETIME(3) NULL,
  ADD COLUMN `deletedAt` DATETIME(3) NULL;
